name: Deployment

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: ok-nick/setup-aftman@v0.4.2
      name: Install aftman
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

    -run: rojo build -o game.rbxl

    -run: rbxcloud experience publish --filename game.rbxl --place-id 18449133471 --universe-id 6252511605 --version-type published --api-key pJhV+oWsSkWiABDcbrh3+KD+oh65fZTFUl8nP1KMW3WNlOV3ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluTnBaeTB5TURJeExUQTNMVEV6VkRFNE9qVXhPalE1V2lJc0luUjVjQ0k2SWtwWFZDSXNJbU4wZVNJNklrcFhWQ0o5LmV5SmlZWE5sUVhCcFMyVjVJam9pY0Vwb1ZpdHZWM05UYTFkcFFVSkVZMkp5YURNclMwUXJiMmcyTldaYVZFWlZiRGh1VURGTFRWY3pWMDVzVDFZeklpd2liM2R1WlhKSlpDSTZJakUyT1RZMk5qYzBJaXdpWVhWa0lqb2lVbTlpYkc5NFNXNTBaWEp1WVd3aUxDSnBjM01pT2lKRGJHOTFaRUYxZEdobGJuUnBZMkYwYVc5dVUyVnlkbWxqWlNJc0ltVjRjQ0k2TVRjeU1EYzJOek13TWl3aWFXRjBJam94TnpJd056WXpOekF5TENKdVltWWlPakUzTWpBM05qTTNNREo5LmZ6QzZMM2dFcXNUMWwxS09oNVhPalRDSGR0dmxEVlRHRWpRZ2paYlFjSjFrZkxEVUp4ZDFoR3pWdnpRR0J5TVNiZGw5TUhfZFlBSUFyaFdVMERLalo1YkotUHFTbC1MbUlEV211b0NtR0FsZGdkNy1Nc1lsQ0hrZTY1bVlkY3VZQ0RjeC1WNDQtdFZaQU1mZlU0aElaR1ZIUGV6a0VJUDBMWlBmcVBYWEdYUDNPTkdsb2dRMkZsS1JELVVVOGxzLUpLWGE0XzFuR0FXQ1NtbFhjRndlZHZsWTZCOFEwdDlNRVJTNHJ0aEk0UUJBb0gweVpHb3I4WXpPeGJleDZQTG1STWhJLVYwMEEzdmJBaVoway1Vd2V3T0xCOTkzdXFPZG5XQWVsV3RxVVZXa1BHWTdndmZPTGVfR1NzbkVneER3c254ZG5DVEhyOVdYUGx0X2JSUUVfQQ==